#pragma once

/* Select hand configuration */
#define MASTER_LEFT
// #define EE_HANDS

//#define RGBLED_NUM 60
#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define AUTO_SHIFT_TIMEOUT 175

//To sync led data on split keyboard
#define SPLIT_LAYER_STATE_ENABLE

#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP

#define ENABLE_RGB_MATRIX_KEYPRESSES  // reacts to keypresses
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_SOLID_SPLASH
